version: '3.2'
services:
  db:
    container_name: db-data
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=qwerty
      - MYSQL_DATABASE=data
      - MYSQL_USER=user
      - MYSQL_PASSWORD=secret
    ports:
      - "9000:3306"
    volumes:
      - ../../.data/db:/var/lib/mysql
    command: [
      'mysqld',
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci',
      #      '--max_allowed_packet=256M',
    ]