version: '3.2'
services:
  db:
    container_name: db-ads
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=verysecret
      - MYSQL_DATABASE=ads
      - MYSQL_USER=user
      - MYSQL_PASSWORD=secret
    ports:
      - "1111:3306"
    volumes:
      - ../../.data/db:/var/lib/mysql
    command: [
      'mysqld',
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci',
      #      '--max_allowed_packet=256M',
    ]